// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5fVfbRw_668kmety9q7f884esPZXZkFk',
    appId: '1:659375746586:web:d44e2f72640a2ddd72eba3',
    messagingSenderId: '659375746586',
    projectId: 'authexample-a68b0',
    authDomain: 'authexample-a68b0.firebaseapp.com',
    storageBucket: 'authexample-a68b0.appspot.com',
    measurementId: 'G-FTZ8B5S41P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNgj_uTJdKGRjlrjuHx9qzujAVSpF70o',
    appId: '1:659375746586:android:3b6f01c26e2b4d9672eba3',
    messagingSenderId: '659375746586',
    projectId: 'authexample-a68b0',
    storageBucket: 'authexample-a68b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvrTzqvfHGTZc6eQ1ZijWeKaoBa3oG0I',
    appId: '1:659375746586:ios:72d0dbdb2a94c1bb72eba3',
    messagingSenderId: '659375746586',
    projectId: 'authexample-a68b0',
    storageBucket: 'authexample-a68b0.appspot.com',
    iosClientId: '659375746586-7mu93em3he8ks2kg6ivuau4c7fusqirt.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvrTzqvfHGTZc6eQ1ZijWeKaoBa3oG0I',
    appId: '1:659375746586:ios:72d0dbdb2a94c1bb72eba3',
    messagingSenderId: '659375746586',
    projectId: 'authexample-a68b0',
    storageBucket: 'authexample-a68b0.appspot.com',
    iosClientId: '659375746586-7mu93em3he8ks2kg6ivuau4c7fusqirt.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );
}
